### ISSUE TITLE
Questions about pyFDAP graphs

### ISSUE THREAD

**Issue by aflores09** [alexblaessle/PyFDAP#1]
Hi Alex,

Thanks so much for the user friendly improvements of the software.  I have a few questions about formatting the graphs to use for publication.

1.  Is is possible to change the x-axis from seconds to minutes?
2.  Can more than one molecule be illustrated on one graph?  For example, can I display 2 or 3 curves with different treatment groups on the same graph?
3.  Is it necessary to adjust the time scale if the raw data inserted into the molecule starts 5 minutes after photoconversion? does this dramatically effect the half-life?
4.  When you enter the background dataset does the software automatically take it into account for each embryo within one molecule?
5.  The # for the noise from my microscope was ~40.  The input box did not accept this number.

If it is easier to troubleshoot via phone I am also available for that.  Thank you for you assistance!

Sincerely,

Andrea Flores

**Comment by alexblaessle** [comment]
Hi @aflores09 , 

1. I've added a plot editor in commit https://github.com/alexblaessle/PyFDAP/commit/9564fa07bf5eccca271305a3bbd00c699d1df59f . Select the plot you want to edit and go to _Edit -> Plotting -> Edit current Plot_ . However, I recommend saving the plot afterwards in eps/pdf format  (_Edit ->Export -> Plot_ ) and load it with a vector graphic software such as adobe illustrator to bring it into a nicer form.

2. Also have been added https://github.com/alexblaessle/PyFDAP/commit/9564fa07bf5eccca271305a3bbd00c699d1df59f. You can find the new plotting options in _Fitting -> Plotting -> Compare Molecules_ .

3. That depends on how long the experiment takes in total. If it takes 10hours, then 5 min are neglectable. But the csv read-in function should already account for that (At least the newest version will do that). 

4. As soon as you analyzed the background datasets again, yes.

5. I think you are talking about the dialog for reading in embryos from csv sheets? This bug has been fixed in commit https://github.com/alexblaessle/PyFDAP/commit/9c1f93b08dfdc12d6bda6fd59ca38c9ea41576ef.
